server:
  port: 8084

spring:
  application:
    name: payment-service
  # TODO: configure datasource / mongo / redis / kafka here

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
