/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReschedulePnrRouteImport } from './routes/reschedule/$pnr'
import { Route as BookingPnrRouteImport } from './routes/booking/$pnr'
import { Route as BookFlightIdRouteImport } from './routes/book/$flightId'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReschedulePnrRoute = ReschedulePnrRouteImport.update({
  id: '/reschedule/$pnr',
  path: '/reschedule/$pnr',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPnrRoute = BookingPnrRouteImport.update({
  id: '/booking/$pnr',
  path: '/booking/$pnr',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFlightIdRoute = BookFlightIdRouteImport.update({
  id: '/book/$flightId',
  path: '/book/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/check-in': typeof CheckInRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/book/$flightId': typeof BookFlightIdRoute
  '/booking/$pnr': typeof BookingPnrRoute
  '/reschedule/$pnr': typeof ReschedulePnrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/check-in': typeof CheckInRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/book/$flightId': typeof BookFlightIdRoute
  '/booking/$pnr': typeof BookingPnrRoute
  '/reschedule/$pnr': typeof ReschedulePnrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/check-in': typeof CheckInRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/book/$flightId': typeof BookFlightIdRoute
  '/booking/$pnr': typeof BookingPnrRoute
  '/reschedule/$pnr': typeof ReschedulePnrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/check-in'
    | '/login'
    | '/search'
    | '/trips'
    | '/book/$flightId'
    | '/booking/$pnr'
    | '/reschedule/$pnr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/check-in'
    | '/login'
    | '/search'
    | '/trips'
    | '/book/$flightId'
    | '/booking/$pnr'
    | '/reschedule/$pnr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/check-in'
    | '/login'
    | '/search'
    | '/trips'
    | '/book/$flightId'
    | '/booking/$pnr'
    | '/reschedule/$pnr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckInRoute: typeof CheckInRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  TripsRoute: typeof TripsRoute
  BookFlightIdRoute: typeof BookFlightIdRoute
  BookingPnrRoute: typeof BookingPnrRoute
  ReschedulePnrRoute: typeof ReschedulePnrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reschedule/$pnr': {
      id: '/reschedule/$pnr'
      path: '/reschedule/$pnr'
      fullPath: '/reschedule/$pnr'
      preLoaderRoute: typeof ReschedulePnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$pnr': {
      id: '/booking/$pnr'
      path: '/booking/$pnr'
      fullPath: '/booking/$pnr'
      preLoaderRoute: typeof BookingPnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$flightId': {
      id: '/book/$flightId'
      path: '/book/$flightId'
      fullPath: '/book/$flightId'
      preLoaderRoute: typeof BookFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckInRoute: CheckInRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  TripsRoute: TripsRoute,
  BookFlightIdRoute: BookFlightIdRoute,
  BookingPnrRoute: BookingPnrRoute,
  ReschedulePnrRoute: ReschedulePnrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
